[main]
    extraCommands = ["git push", "git push --tags"]
  version   = "1.0.0"
  tag       = true
  serialize = "{version}-{banner}"
[[operate]]
  location = "cmd/FileNotifier/main.go"
  search   = "__version__ = \"{}\""
  replace  = "__version__ = \"{}\""
